server:
  port: 8080
  servlet.context-path: /znhyAdmin
  servlet:
    session:
      timeout: 432000
spring:
  datasource:
    name: mybatis_test
    #使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #配置基本属性
      url: jdbc:mysql://192.168.1.210/znhy?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    database: 0
    host: 192.168.1.19
    port: 6379
    password: 123456
    jedis:
      pool:
        ##连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ##连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ##连接池最大空闲连接
        max-idle: 5
        ##连接池最小空闲连接数
        min-idle: 0
    ###连接超时时间（毫秒）
    timeout: 10000
              
# 模板配置      
thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8
  cache: false
#mybatis-plus配置
mybatis-plus:
  # 映射文件所在路径
  mapper-locations: classpath:mappers/*.xml
  # pojo类所在包路径
  type-aliases-package: com.auxing.znhy.entity
    
# 日志输出
logging:
  conifg:classpath:logback.xml